### ISSUE TITLE
Scroll to specific section in course

### ISSUE THREAD

**Issue by henriasv** [uio-library/scroll-app#11]

**Comment by danmichaelo** [comment]
#10 and #11 are a bit more intertwined than I first thought.

- #11 can be easily solved with [vue-scrollto](https://www.npmjs.com/package/vue-scrollto).
- #10 can be easily solved with the `accordion` attribute of vue-bootstrap.

But vue-scrollto does not update the animation target *during* the animation, so combining them leads to overshooting:

![accordion-overshoot-opt](https://user-images.githubusercontent.com/434495/44089574-903851e4-9fc7-11e8-9726-0a32a969232e.gif)

**Comment by danmichaelo** [comment]
To orchestrate the two animations we need more low-level control of them, which means some work.

Alternatively, one option could also be to drop animation altogether, or drop only the expand/collapse animation.

**Comment by danmichaelo** [comment]
Merging with #10
