### ISSUE TITLE
Radio selection sometimes doesn't show on QuizWithNavication see-through

### ISSUE THREAD

**Issue by henriasv** [uio-library/scroll-app#2]
When going through exercises after checking the answers ("se igjennom"), sometimes the radio button for the selected element does not show. 

![image](https://user-images.githubusercontent.com/1681822/38869103-d540e7aa-4249-11e8-8b7e-207c6629bd18.png)

**Comment by danmichaelo** [comment]
Explanation here: https://vuejs.org/v2/guide/list.html#key

Takes some time to figure out the first time you hit it...
