### ISSUE TITLE
Text within exercises in not treated as markdown nor HTML.

### ISSUE THREAD

**Issue by henriasv** [uio-library/scroll-app#3]
Text in exercises should support markdown (or at least HTML). Currently, markdown/HTML tags show up as raw text inside exercises.

**Comment by danmichaelo** [comment]
Right, it's escaped by default. We can choose to trust the exercise creators though :)

**Comment by danmichaelo** [comment]
Added [`v-html`](https://vuejs.org/v2/guide/syntax.html#Raw-HTML) a few places, feel free to add it places I missed it.
